AllCops:
  TargetRubyVersion: 2.1

Layout:
  Exclude:
    - pluggy.gemspec

Style/Encoding:
  Exclude:
    - pluggy.gemspec

Metrics/BlockLength:
  Exclude:
    - pluggy.gemspec

Style/HashSyntax:
  Exclude:
    - Rakefile

Lint/UnusedMethodArgument:
  Exclude:
    - lib/pluggy/actions/*

Style/EmptyMethod:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 13

Metrics/LineLength:
  Max: 125

Metrics/AbcSize:
  Max: 16

Style/Documentation:
  Enabled: false
